name = "smaarmstrong/gift-card"
version = "0.0.0"
compiler = "v1.1.5"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'smaarmstrong/gift-card'"

[repository]
user = "smaarmstrong"
project = "gift-card"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
