name = "hello_aiken/smaarmstrong"
version = "0.0.0"
compiler = "v1.1.5"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'hello_aiken/smaarmstrong'"

[repository]
user = "hello_aiken"
project = "smaarmstrong"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
